FROM node:14-alpine
# Créer le répertoire de l'application
WORKDIR /usr/src/app


# Installer les dépendances de l'application
# Un joker est utilisé pour s'assurer que le paquet.json ET le paquet-lock.json sont copiés lorsqu'ils sont disponibles (npm@5+)
COPY ./* /usr/src/app/

RUN npm install -g npm

RUN npm install


# Regroupement des sources de l'application

EXPOSE 8080
CMD [ "npm", "run", "prod" ]