apiVersion: v1
kind: Service
metadata:
  name: api-feed
  labels:
    run: api-feed
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  selector:
    app: api-feed